version: '3.6'
services:
# api - bigquery pipeline
  mage:
    image: mage
    container_name: mage-instance
    ports:
      - 6789:6789
    env_file:
      - .env  # Load environment variables from the .env file

    restart: on-failure:5

  # streamlit dashboard
  dashboard:
    image: streamlit-dashboard  # Use the image name you assigned during Docker build
    container_name: streamlit-dashboard
    ports:
      - 8500:8500  # Expose the port used by Streamlit
    env_file:
      - .env  # Load environment variables from the .env file
    restart: on-failure:5  # Handle restarts
